// 결과별 OG 메타데이터 — worker.js의 SVG 생성기와 HTMLRewriter가 사용.
// 형식 최소화: name, emoji, color, tagline 4개 필드만(SVG 출력에 필요한 것).
// 본문 상세 설명은 각 테스트 HTML의 RESULTS dict에 있고, 여기는 미러링.

export const TEST_META = {
  'plant-mbti': { title: '식물 MBTI', emoji: '🌿' },
  'dev-mbti':   { title: '개발자 유형 MBTI', emoji: '💻' },
  'color-mind': { title: '나의 색깔 심리', emoji: '🎨' },
  'animal-type':{ title: '동물 성격 MBTI', emoji: '🐾' },
};

export const RESULT_DATA = {
  'plant-mbti': {
    INTJ: { name: '분재', emoji: '🪴', color: '#4a8a6a', tagline: '수십 년의 비전으로 한 그루를 완성하는 전략가' },
    INTP: { name: '식충식물', emoji: '🪤', color: '#6a8a4a', tagline: '독특한 메커니즘에 매료되는 사색가' },
    ENTJ: { name: '대나무', emoji: '🎋', color: '#5da57a', tagline: '한번 터지면 누구도 막을 수 없는 폭풍 성장' },
    ENTP: { name: '토마토', emoji: '🍅', color: '#d96a5a', tagline: '어디서나 잘 자라는 다재다능 변종 부자' },
    INFJ: { name: '연꽃', emoji: '🪷', color: '#c878b8', tagline: '흙탕물에서도 빛나는 신비로운 영혼' },
    INFP: { name: '라벤더', emoji: '💜', color: '#b888d8', tagline: '조용히 향기로 세상을 위로하는 존재' },
    ENFJ: { name: '해바라기', emoji: '🌻', color: '#f5c43a', tagline: '주변을 환하게 만드는 햇빛 추종자' },
    ENFP: { name: '야생화', emoji: '🌼', color: '#f5a85a', tagline: '어디든 피어나는 자유로운 영혼' },
    ISTJ: { name: '선인장', emoji: '🌵', color: '#5a8a5a', tagline: '묵묵히 사막에서도 살아남는 강인함' },
    ISFJ: { name: '다육이', emoji: '🪴', color: '#88b070', tagline: '조용히 보살피며 곁을 지키는 친구' },
    ESTJ: { name: '떡갈나무', emoji: '🌳', color: '#7a6a4a', tagline: '튼튼하게 버텨주는 든든한 기둥' },
    ESFJ: { name: '장미', emoji: '🌹', color: '#e85a7a', tagline: '사람들을 끌어모으는 사교적인 매력' },
    ISTP: { name: '알로에', emoji: '🌿', color: '#6a9a7a', tagline: '필요할 때 정확히 도움이 되는 실용주의' },
    ISFP: { name: '제비꽃', emoji: '💜', color: '#9a7ab8', tagline: '조용히 자신만의 색을 피우는' },
    ESTP: { name: '바질', emoji: '🌿', color: '#7ab85a', tagline: '어디에 두어도 활기차게 자라는 활용성' },
    ESFP: { name: '튤립', emoji: '🌷', color: '#f570a0', tagline: '봄을 알리는 화려한 등장' },
  },
  'dev-mbti': {
    INTJ: { name: '아키텍트', emoji: '🏗️', color: '#5a7ab8', tagline: '시스템 전체를 머릿속에서 굴리는 설계 장인' },
    INTP: { name: '분석가', emoji: '🔬', color: '#6a8a9a', tagline: '"왜 이게 이렇게 동작하지?"가 일상인 사색가' },
    ENTJ: { name: '테크 리드', emoji: '🚀', color: '#d96a5a', tagline: '목표를 분해해 사람과 일정을 함께 움직이는 추진력' },
    ENTP: { name: '이노베이터', emoji: '💡', color: '#f0b860', tagline: '"이거 이렇게 한번 해볼까?"의 끝없는 실험가' },
    INFJ: { name: '개발 멘토', emoji: '🧭', color: '#9a78b8', tagline: '말하지 않은 것까지 읽어내는 사려 깊은 안내자' },
    INFP: { name: '크래프트맨', emoji: '🪶', color: '#a890d0', tagline: '코드의 아름다움과 의미에 진심인 장인' },
    ENFJ: { name: '팀 빌더', emoji: '🌟', color: '#f5c43a', tagline: '팀의 분위기를 만들고 모두를 같은 배에 태우는 리더' },
    ENFP: { name: '데브 에반젤리스트', emoji: '🐿️', color: '#f5905a', tagline: '기술의 즐거움을 사방에 퍼뜨리는 에너지원' },
    ISTJ: { name: '미들웨어 장인', emoji: '🛡️', color: '#5a8a5a', tagline: '한 번 맡으면 끝까지 책임지는 신뢰의 기둥' },
    ISFJ: { name: '신뢰의 데브옵스', emoji: '🌾', color: '#88b070', tagline: '조용히 시스템을 살피며 모두의 새벽을 지키는 보호자' },
    ESTJ: { name: '프로젝트 매니저', emoji: '🧱', color: '#8a7a6a', tagline: '일정·범위·품질을 동시에 맞추는 실행의 달인' },
    ESFJ: { name: '풀스택 코디네이터', emoji: '🎉', color: '#e87a90', tagline: '프론트·백·디자인·QA를 매끄럽게 잇는 다리' },
    ISTP: { name: '시스템 트러블슈터', emoji: '🐺', color: '#6a9a8a', tagline: '장애 발생 시 가장 침착하고 가장 유능한 정비공' },
    ISFP: { name: 'UX 크리에이터', emoji: '🎨', color: '#b890d0', tagline: '디테일 하나에 사용자 경험이 달라진다고 믿는 감성가' },
    ESTP: { name: '해커톤 챔피언', emoji: '⚡', color: '#7ab85a', tagline: '24시간 안에 데모 가능한 결과를 뽑아내는 스피드 러너' },
    ESFP: { name: '데모 데이 스타', emoji: '🎢', color: '#f570a0', tagline: '무대를 즐기고 청중과 함께 호흡하는 발표의 달인' },
  },
  'color-mind': {
    INTJ: { name: '딥 네이비', emoji: '🟦', color: '#1a2a5a', tagline: '깊고 차분한 사색의 푸름' },
    INTP: { name: '미스트 그레이', emoji: '🌫️', color: '#8a9aa8', tagline: '안개처럼 모든 가능성을 품은 회색' },
    ENTJ: { name: '크림슨', emoji: '🟥', color: '#b8204a', tagline: '한번 보면 잊을 수 없는 결단의 진홍' },
    ENTP: { name: '선셋 오렌지', emoji: '🟧', color: '#f58a3a', tagline: '석양처럼 매 순간 다른 빛깔의 변주가' },
    INFJ: { name: '라일락', emoji: '🟣', color: '#b89adb', tagline: '은은한 향과 함께 마음에 스며드는 보라' },
    INFP: { name: '라벤더', emoji: '🟪', color: '#a890d8', tagline: '향기로 사람의 마음을 데우는 부드러운 보라' },
    ENFJ: { name: '골든 옐로우', emoji: '🟨', color: '#f5c43a', tagline: '주변을 환하게 만드는 따뜻한 태양' },
    ENFP: { name: '코랄 핑크', emoji: '🪸', color: '#f5807a', tagline: '산호초처럼 다채로운 매력의 따뜻한 핑크' },
    ISTJ: { name: '포레스트 그린', emoji: '🌲', color: '#2a6a3a', tagline: '오랜 숲처럼 흔들리지 않는 깊은 초록' },
    ISFJ: { name: '소프트 베이지', emoji: '🟫', color: '#d4b896', tagline: '어디에 두어도 편안한 위로의 색' },
    ESTJ: { name: '버건디', emoji: '🟤', color: '#6a1a2a', tagline: '와인처럼 깊이 우러나는 권위의 적포도주' },
    ESFJ: { name: '체리 핑크', emoji: '🌸', color: '#f570a0', tagline: '벚꽃처럼 사람을 모으는 사랑스러운 핑크' },
    ISTP: { name: '스틸 그레이', emoji: '⚙️', color: '#6a7a8a', tagline: '단단하고 차분한 도구의 색' },
    ISFP: { name: '민트', emoji: '🌿', color: '#9adcb8', tagline: '청량하고 다정한 봄의 새싹' },
    ESTP: { name: '라임 그린', emoji: '💚', color: '#8adc4a', tagline: '달리고 싶어지는 톡톡 튀는 라임' },
    ESFP: { name: '마젠타', emoji: '🩷', color: '#d83aa0', tagline: '무대 위 가장 빛나는 등장의 색' },
  },
  'animal-type': {
    INTJ: { name: '늑대', emoji: '🐺', color: '#5a6a8a', tagline: '달빛 아래 무리를 이끄는 전략가' },
    INTP: { name: '부엉이', emoji: '🦉', color: '#7a6a8a', tagline: '밤의 정적 속에서 모든 것을 관찰하는 현자' },
    ENTJ: { name: '사자', emoji: '🦁', color: '#d99a3a', tagline: '사바나의 햇살 아래 모두를 이끄는 자연스러운 왕' },
    ENTP: { name: '여우', emoji: '🦊', color: '#f5904a', tagline: '꾀와 호기심으로 어디든 살아남는 트릭스터' },
    INFJ: { name: '사슴', emoji: '🦌', color: '#a890c0', tagline: '숲 속에서 모든 것을 느끼는 섬세한 영혼' },
    INFP: { name: '토끼', emoji: '🐰', color: '#d8a8c8', tagline: '순수한 마음으로 작은 행복을 찾는 여린 영혼' },
    ENFJ: { name: '돌고래', emoji: '🐬', color: '#5abaef', tagline: '무리의 분위기를 만들고 모두를 함께 헤엄치게 하는 인도자' },
    ENFP: { name: '다람쥐', emoji: '🐿️', color: '#f5a86a', tagline: '나무 사이를 자유롭게 누비는 끝없는 호기심' },
    ISTJ: { name: '곰', emoji: '🐻', color: '#6a5a4a', tagline: '꾸준한 책임감으로 자기 영역을 지키는 든든한 보호자' },
    ISFJ: { name: '양', emoji: '🐑', color: '#c8b8a0', tagline: '무리를 따뜻하게 감싸 안는 조용한 보살핌' },
    ESTJ: { name: '호랑이', emoji: '🐯', color: '#dc7a3a', tagline: '영역을 지키는 카리스마와 자존심의 왕' },
    ESFJ: { name: '강아지', emoji: '🐶', color: '#f59a7a', tagline: '사람들을 모이게 하는 무조건적 사랑의 발산' },
    ISTP: { name: '표범', emoji: '🐆', color: '#7a8a8a', tagline: '소리 없이 정확히 움직이는 침착한 정비공' },
    ISFP: { name: '고양이', emoji: '🐱', color: '#c8a8d0', tagline: '자기만의 결을 가진 자유로운 영혼' },
    ESTP: { name: '매', emoji: '🦅', color: '#a85a3a', tagline: '하늘 위에서 정확히 목표를 향해 내려꽂는 속도' },
    ESFP: { name: '앵무새', emoji: '🦜', color: '#f5704a', tagline: '무리의 분위기를 화려하게 만드는 자유로운 엔터테이너' },
  },
};
